language: go

go:
  - 1.12
  - tip

env:
- GO111MODULE=on

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - wget -O - -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh

script:
  - ./bin/golangci-lint run
  - go test -v -race ./...

after_success:
  - test "$TRAVIS_GO_VERSION" = "1.12" && goveralls -service=travis-ci
